# [General]
wallpaper_dir = /home/oliver/wallpaper/default
rotation_interval = 60
randomize = true
backend = hyprpaper

# [hyprpaper settings]
# available modes: cover, contain, tile, fill
hyprpaper_mode = contain
monitor_name = all
