set -g default-terminal "tmux-256color"

# Start windows and panes at 1 instead of 0
set -g base-index 1
set -g mouse on

set -g xterm-keys on
set -s extended-keys on
set -g terminal-features 'xterm*:extkeys'
set -g allow-passthrough on
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

bind r source-file ~/.tmux.conf

# split panes using | and -
bind | split-window -h
bind - split-window -v

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

bind s choose-tree -s
bind Space switch-client -l
bind C-c switch -t config
bind C-h switch -t bueno
bind C-t switch -t ops

# Plugins
set -g @plugin 'tmuxpack/tpack'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

# set -g @plugin 'TechnicalDC/tmux-ayu-theme'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-show-fahrenheit false
set -g @dracula-show-flags true
set -g @dracula-plugins "cpu-usage ram-usage battery"
set -g @dracula-show-left-icon session

set -g @dracula-show-battery-status true
set -g @dracula-battery-label false

set -g @dracula-show-empty-plugins true
set -g status-position top

# Restore neovim session after reboot
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpack/tpm'
