[tools]
python = "latest"
node = "22"
chezmoi = "2.61"
pre-commit = "latest"
go = "1.21"
zellij = "latest"
"asdf:neovim" = "ref:v0.11.0"
pnpm = "10.11"
gh = "2.69"
neovim = "0.11.2"
lazygit = "latest"
cmake = "latest"
tokei = "latest"
yazi = "latest"
typst = "0.13.1"
lua = "latest"
dotnet = "latest"

[settings]

[settings.aqua]
slsa = false

[settings.python]
compile = false
