[tools]
	"github:agavra/tuicr" = "latest"
	"github:anthropics/claude-code" = "latest"
	"github:coleam00/archon" = "latest"
	"github:dlvhdr/diffnav" = "latest"
	"github:openfga/cli" = "latest"
	"github:openfga/openfga" = "latest"
	"github:pamburus/hl" = "latest"
	act = "0.2.89"
	azure-cli = "2"
	biome = "2"
	bun = "latest"
	caddy = "latest"
	chezmoi = "latest"
	claude = "latest"
	cmctl = "latest"
	delta = "latest"
	direnv = "latest"
	dotnet = "10.0.300"
	eza = "latest"
	flux2 = "2.7"
	fzf = "latest"
	gh = "2.82.1"
	go = "1.21"
	harper-cli = "latest"
	hk = "1.55"
	java = "latest"
	k3d = "latest"
	k9s = "latest"
	lazydocker = "latest"
	lazygit = "0.60"
	linkerd = "latest"
	lua = "latest"
	neovim = "0.12.4"
	node = "24"
	oh-my-posh = "latest"
	opencode = "1.18"
	pi = "latest"
	pkl = "latest"
	pnpm = "11.10"
	pre-commit = "latest"
	python = "3.14.6"
	ripgrep = "latest"
	rtk = "0.43"
	rust = "latest"
	spectral = "latest"
	taplo = "latest"
	tmux = "latest"
	tokei = "latest"
	tree-sitter = "latest"
	typst = "0.14.2"
	uv = "latest"
	yamllint = "latest"
	yazi = "latest"
	yq = "latest"
	yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
	zoxide = "latest"

[settings]
	not_found_auto_install = false
	idiomatic_version_file_enable_tools = ["python"]

	[settings.aqua]
		slsa = false

	[settings.python]
		compile = false
