theme = "ayu_evolve"

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80]

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "position-percentage",
  "total-line-numbers",
  "separator",
  "file-encoding",
  "file-line-ending",
]

[editor.whitespace.render]
space = "none"
tab = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true
